name:                twoba
version:             0.1.0.0
github:              pparkkin/twoba
#license:             BSD3
author:              Paavo Parkkinen
maintainer:          pparkkin@gmail.com
copyright:           2017 Paavo Parkkinen

extra-source-files:
- README.md

# Metadata used when publishing your package
#synopsis:            Short description of your package
#category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
#description:         Please see the README on Github at <https://github.com/pparkkin/twoba#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- linear
- random
- scotty
- split
- text
- wai-extra
- wai-middleware-static
- wai-websockets
- warp
- websockets

library:
  source-dirs: src

executables:
  twoba-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twoba
  twoba-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twoba

tests:
  twoba-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twoba
    - hspec
